contact_list:
  path: /
  controller: App\Controller\ContactController::list
  methods: GET

contact_create:
  path: /contact/create
  controller: App\Controller\ContactController::create
  methods: GET|POST

contact_edit:
  path: /{slug}
  controller: App\Controller\ContactController::edit
  methods: GET|POST

contact_delete:
  path: /{slug}/delete
  controller: App\Controller\ContactController::delete
  methods: GET
